//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltranApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Todo
    {
        public int TodoId { get; set; }
        public int UserId { get; set; }

        [Required(ErrorMessage = "Title is required!!")]
        public string Title { get; set; }
        public bool State { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
    }
}
